<a href="https://colab.research.google.com/github/soyebganja/DL-Practice-Projects/blob/main/7%3ANeural%20Networks%20in%20PyTorch/7_1_Employee_Bonus_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [113]:
df = pd.read_csv('bonus.csv')
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [114]:
df.shape

(1000, 5)

In [115]:
from re import X
from sklearn.model_selection import train_test_split

X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [116]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [117]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [118]:
class BonusPredictor(nn.Module):
  def __init__(self):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(3, 1) # 3 input feature and 1 output neuron
    )
  def forward(self, x):
    return self.network(x)

In [119]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.007)

In [120]:
epochs = 5000

for epoch in range(epochs):
  # 1. Forward pass
  predictions = model(X_train_tensor)
  loss = criterion(predictions, y_train_tensor)

  # 2. Backward pass
  optimizer.zero_grad()
  loss.backward()

  # 3. update weights
  optimizer.step()

  # print loss every 100 epoch
  if epoch % 100 == 0:
    print(f'Epoch: [{epoch+1} / {epochs}], Loss: {loss.item():.2f}')

Epoch: [1 / 5000], Loss: 18998.59
Epoch: [101 / 5000], Loss: 18.85
Epoch: [201 / 5000], Loss: 15.54
Epoch: [301 / 5000], Loss: 12.95
Epoch: [401 / 5000], Loss: 10.83
Epoch: [501 / 5000], Loss: 9.06
Epoch: [601 / 5000], Loss: 7.58
Epoch: [701 / 5000], Loss: 6.34
Epoch: [801 / 5000], Loss: 5.30
Epoch: [901 / 5000], Loss: 4.44
Epoch: [1001 / 5000], Loss: 3.71
Epoch: [1101 / 5000], Loss: 3.11
Epoch: [1201 / 5000], Loss: 2.60
Epoch: [1301 / 5000], Loss: 2.18
Epoch: [1401 / 5000], Loss: 1.82
Epoch: [1501 / 5000], Loss: 1.52
Epoch: [1601 / 5000], Loss: 1.27
Epoch: [1701 / 5000], Loss: 1.07
Epoch: [1801 / 5000], Loss: 0.89
Epoch: [1901 / 5000], Loss: 0.75
Epoch: [2001 / 5000], Loss: 0.62
Epoch: [2101 / 5000], Loss: 0.52
Epoch: [2201 / 5000], Loss: 0.44
Epoch: [2301 / 5000], Loss: 0.37
Epoch: [2401 / 5000], Loss: 0.31
Epoch: [2501 / 5000], Loss: 0.26
Epoch: [2601 / 5000], Loss: 0.21
Epoch: [2701 / 5000], Loss: 0.18
Epoch: [2801 / 5000], Loss: 0.15
Epoch: [2901 / 5000], Loss: 0.13
Epoch: [3001 /

In [121]:
model.eval()

with torch.no_grad():
  test_predictions = model(X_test_tensor)
  test_loss = criterion(test_predictions, y_test_tensor)

print(f'Test Loss: {test_loss.item():.2f}')

Test Loss: 0.00


In [122]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [123]:
test_predictions[:3]

tensor([[190.],
        [150.],
        [114.]])

In [124]:
y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [125]:
# w1= 12, w2 = 6 , w3 = 2, bais = 20

for name, value in model.named_parameters():
  print(f"Name: {name}, Value: {value}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0089,  5.9578,  2.0503]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([19.7943], requires_grad=True)
